#!/bin/bash
set -e

go get github.com/kr/godep
go install github.com/kr/godep

export PATH="$GOPATH/bin:$PATH"

OLD_PWD="$PWD"
cd "$(dirname "$0")/cli"
    export GOPATH="$(godep path):$GOPATH"

    godep restore

    godep go install github.com/jeremybanks/go-distributed/gtkgui/distributedgtk
cd "$OLD_PWD"

go fmt github.com/jeremybanks/go-distributed/bencoding
go fmt github.com/jeremybanks/go-distributed/dht
go fmt github.com/jeremybanks/go-distributed/utils
go fmt github.com/jeremybanks/go-distributed/torrent
go fmt github.com/jeremybanks/go-distributed/cli
go fmt github.com/jeremybanks/go-distributed/cli/distributed

go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/bencoding
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/dht
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/utils
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/torrent
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/cli
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/cli/distributed

PATH="$GOPATH/bin:$PATH" distributed $*
