#!/bin/bash
set -e

export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig # XXX: only correct for OS X Homebrew users

go fmt github.com/jeremybanks/go-distributed/gtkgui
go fmt github.com/jeremybanks/go-distributed/gtkgui/distributedgtk

go install github.com/mattn/go-gtk/gtk
go install github.com/jeremybanks/go-distributed/gtkgui
go install github.com/jeremybanks/go-distributed/gtkgui/distributedgtk

go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/gtkgui
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/gtkgui/distributedgtk

"$GOPATH/bin/distributedgtk" $*
