#!/bin/bash
set -e

go get github.com/kr/godep
go install github.com/kr/godep

export PATH="$GOPATH/bin:$PATH"

export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig # XXX: only correct for OS X Homebrew users

OLD_PWD="$PWD"
cd "$(dirname "$0")/cli"
    godep install github.com/jeremybanks/go-distributed/cli/distributed

    godep go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/bencoding
    godep go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/dht
    godep go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/utils
    godep go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/torrent
    godep go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/cli
    godep go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/cli/distributed
cd "$OLD_PWD"

cd "$(dirname "$0")/gtkgui"
    godep install github.com/jeremybanks/go-distributed/gtkgui/distributedgtk

    go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/bencoding
    go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/dht
    go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/utils
    go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/torrent
    go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/cli
    go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/cli/distributed
cd "$OLD_PWD"
