#!/bin/bash
set -e

go install github.com/jeremybanks/go-distributed/bencoding
go install github.com/jeremybanks/go-distributed/dht
go install github.com/jeremybanks/go-distributed/utils
go install github.com/jeremybanks/go-distributed/torrent
go install github.com/jeremybanks/go-distributed/cli
go install github.com/jeremybanks/go-distributed/cli/distributed
go install github.com/jeremybanks/go-distributed/gtkgui
go install github.com/jeremybanks/go-distributed/gtkgui/distributedgtk

go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/bencoding
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/dht
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/utils
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/torrent
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/cli
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/cli/distributed
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/gtkgui
go test -run=. -bench=NONE github.com/jeremybanks/go-distributed/gtkgui/distributedgtk
